# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2025-01-06 17:37:02
"""
import arcpy
from sys import argv

#For inline variable substitution, parameters passed as a String are evaluated using locals(), globals() and isinstance(). To override, substitute values directly.
def Model1(Aggregationsebene="C:\\Users\\ygerling\\Studium ZEUS\\2. Semester\\2.3 Projekt ZEUS - WWNW\\Wärmelyse T6 Geodaten\\Eingangsdaten Wärmepotenziale.gdb\\Lambert_Raster_Bremen_100m", Wärmebedarfsdaten="C:\\Users\\ygerling\\Studium ZEUS\\2. Semester\\2.3 Projekt ZEUS - WWNW\\Wärmelyse T6 Geodaten\\Eingangsdaten Wärmepotenziale.gdb\\DBI_Wärmedaten"):  # Wärmepotenziale Teil-Workflow

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    arcpy.ImportToolbox(r"c:\users\ygerling\appdata\local\programs\arcgis\pro\Resources\ArcToolbox\toolboxes\GeoAnalytics Desktop Tools.tbx")
    Zusammenfassungsfelder = [["WB_kWh", "SUM"]]

    # Process: Punkte aggregieren (Punkte aggregieren) (gapro)
    Wärmepotenziale_aggregiert = "C:\\Users\\ygerling\\Studium ZEUS\\2. Semester\\2.3 Projekt ZEUS - WWNW\\Wärmelyse T6 Geodaten\\Ergebnis Wärmepotenziale.gdb\\Wärmepotenziale_aggregiert"
    arcpy.gapro.AggregatePoints(point_layer=Wärmebedarfsdaten.__str__().format(**locals(),**globals())if isinstance(Wärmebedarfsdaten, str) else Wärmebedarfsdaten, out_feature_class=Wärmepotenziale_aggregiert, polygon_or_bin="POLYGON", polygon_layer=Aggregationsebene.__str__().format(**locals(),**globals())if isinstance(Aggregationsebene, str) else Aggregationsebene, summary_fields=Zusammenfassungsfelder)

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace="C:\\Users\\ygerling\\Studium ZEUS\\2. Semester\\2.3 Projekt ZEUS - WWNW\\Wärmelyse T6 Geodaten\\Default.gdb", workspace="C:\\Users\\ygerling\\Studium ZEUS\\2. Semester\\2.3 Projekt ZEUS - WWNW\\Wärmelyse T6 Geodaten\\Default.gdb"):
        Model1(*argv[1:])
